config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "boards#index"

  resources :boards do
    resources :cards, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :cards, dependent: :destroy
  belongs_to :user
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#
# Indexes
#
#  index_cards_on_board_id  (board_id)
#
class Card < ApplicationRecord
  belongs_to :board
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  
  def display_name
    self.email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_article, only: [:edit, :update]
  
  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path(@board), notice: '保存できたよ'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
    @cards = @board.cards
  end

  def edit
  end

  def update
    if @board .update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end

  def set_article
    @board = current_user.boards.find(params[:id])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    board = Board.find(params[:board_id])
    @card = board.cards.build
  end

  def create
    board = Board.find(params[:board_id])
    @card = board.cards.build(card_params)
    if @card.save
      redirect_to board_path(board), notice: 'カードを追加'
    else
      flash.now[:error] = '更新できませんでした'
      render :new
    end
  end

  private
  def card_params
    params.require(:card).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
%div
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  %h1
    New Board
  = form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f|
    %div
    = f.label :title, 'title'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'content'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/index.html.haml
%h1
  ALL Boards
- @boards.each do |board|
  %div.many-card
    %h2
      = board.title 
    %p
      = board.content
    - if board.user.present?
      %p= board.user.display_name
    .board_detail_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to '編集する', edit_board_path(board)
          = link_to '削除する', board_path(board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
%div.card_new
  %h2
    + Add new boards

app/views/boards/new.html.haml
%div
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  %h1
    New Board
  = form_with(model: @board, url: boards_path, method: 'post', local: true) do |f|
    %div
    = f.label :title, 'title'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, 'content'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/show.html.haml
.board
  %h1.board_title= @board.title
  .board_content
    = @board.content
  .image_profile
    = image_tag '123456.png', class: 'profile_image'

.board
  %h2 カード一覧
  - @cards.each do |card|
    .board_card
      %p= card.title
      %p= card.content

app/views/borads/new.html.haml
%h1
  New Board
= form_with(model: @borad, url: borads_path, method: 'post', local: true) do |f|
  %div
  = f.label :title, 'name'
  %div
    = f.text_field :title, class: 'text'
  %div
    = f.label :content, 'Description'
  %div
    = f.text_area :content
  = f.submit 'Submit', class: 'btn-primary'

app/views/cards/new.html.haml
.container
  %ul
    - @card.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @card, url: board_cards_path(@card.board), local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_area :title
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NikaTodo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      .image_profile
        = image_tag '123456.png', class: 'header_back'
      .header_logos
        %p.header_title
          Boardas
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield